# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_indicator <- function(x) {
    .Call(`_rfnorm_rcpp_indicator`, x)
}

rcpp_FN_Sampling_2d <- function(number, mu, sig) {
    .Call(`_rfnorm_rcpp_FN_Sampling_2d`, number, mu, sig)
}

#' Folded Normal 2D RNG with Gibbs Sampling
#'
#' Generate Random Number for 2-d Folded Normal with Gibss Sampling
#' @param N sample size
#' @param x_init vector of length 2, initial value
#' @param sig1 variance[1,1]
#' @param sig2 variance[2,2]
#' @param rho rho
#' @return matrix of N*2
rcpp_Gibbs_2d <- function(N, x_init, sig1, sig2, rho) {
    .Call(`_rfnorm_rcpp_Gibbs_2d`, N, x_init, sig1, sig2, rho)
}

