// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_indicator
int rcpp_indicator(NumericVector& x);
RcppExport SEXP _rfnorm_rcpp_indicator(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_indicator(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_FN_Sampling_2d
List rcpp_FN_Sampling_2d(int number, double mu, double sig);
RcppExport SEXP _rfnorm_rcpp_FN_Sampling_2d(SEXP numberSEXP, SEXP muSEXP, SEXP sigSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type number(numberSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sig(sigSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_FN_Sampling_2d(number, mu, sig));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_Gibbs_2d
NumericMatrix rcpp_Gibbs_2d(int N, NumericVector x_init, double sig1, double sig2, double rho);
RcppExport SEXP _rfnorm_rcpp_Gibbs_2d(SEXP NSEXP, SEXP x_initSEXP, SEXP sig1SEXP, SEXP sig2SEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_init(x_initSEXP);
    Rcpp::traits::input_parameter< double >::type sig1(sig1SEXP);
    Rcpp::traits::input_parameter< double >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_Gibbs_2d(N, x_init, sig1, sig2, rho));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_NumEx();
RcppExport SEXP _rcpp_module_boot_yada();
RcppExport SEXP _rcpp_module_boot_stdVector();

static const R_CallMethodDef CallEntries[] = {
    {"_rfnorm_rcpp_indicator", (DL_FUNC) &_rfnorm_rcpp_indicator, 1},
    {"_rfnorm_rcpp_FN_Sampling_2d", (DL_FUNC) &_rfnorm_rcpp_FN_Sampling_2d, 3},
    {"_rfnorm_rcpp_Gibbs_2d", (DL_FUNC) &_rfnorm_rcpp_Gibbs_2d, 5},
    {"_rcpp_module_boot_NumEx", (DL_FUNC) &_rcpp_module_boot_NumEx, 0},
    {"_rcpp_module_boot_yada", (DL_FUNC) &_rcpp_module_boot_yada, 0},
    {"_rcpp_module_boot_stdVector", (DL_FUNC) &_rcpp_module_boot_stdVector, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rfnorm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
